// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File information for instance file browser
 */
export type FileInfo = {
  name: string;
  path: string;
  isDirectory: boolean;
  size: bigint;
  modified: bigint;
};

export type GameExitedEvent = {
  instanceId: string;
  versionId: string;
  exitCode: number | null;
  wasStopped: boolean;
};

export type GithubRelease = {
  tagName: string;
  name: string;
  publishedAt: string;
  body: string;
  htmlUrl: string;
};

/**
 * Installed version info
 */
export type InstalledVersion = { id: string; type: string };

/**
 * Migrate instance caches to shared global caches
 */
export type MigrationResult = {
  movedFiles: number;
  hardlinks: number;
  copies: number;
  savedBytes: bigint;
  savedMb: number;
};

export type PastebinResponse = { url: string };

/**
 * Version metadata for display in the UI
 */
export type VersionMetadata = {
  id: string;
  javaVersion: bigint | null;
  isInstalled: boolean;
};
